name: Go

on:
  workflow_dispatch:

env:
  GITHUB_NAME: czy13724
  GITHUB_EMAIL: contact@levifree.tech
  STARED_NUMBER: 10

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: My GitHub Status
        uses: yihong0618/github-readme-stats@main
        with:
          WITH_STARED: false
          TELEGRAM_TOKEN: ${{ secrets.TELE_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELE_CHAT_ID }}
